name: untitled_2
timestamp: 1448392388
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1448392388
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
