preset: preset2
header:
  background: '#75787a'
  text-color: '#ffffff'
showcase:
  background: '#73a5f5'
main:
  background: '#ffffff'
  text-color: '#666666'
navigation:
  background: '#3180c2'
  text-color: '#ffffff'
  overlay: 'rgba(0, 0, 0, 0.4)'
